[package]
name = "rags"
version = "0.1.0"
authors = ["mxheller <heller.max1@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "^0.4.6"
failure = "0.1.5"
min-max-heap = "^1.2.2"
prettytable-rs = "^0.8.0"
regex = "^1.1.6"
structopt = "^0.2.15"

[dev-dependencies]
tempfile = "3.1.0"
